import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:igclone/resources/auth_methods.dart';
import 'package:igclone/responsive/mobile_screen_layout.dart';
import 'package:igclone/responsive/responsive_layout.dart';
import 'package:igclone/responsive/web_screen_layout.dart';
// import 'package:igclone/screens/signup_screen.dart';
import 'package:igclone/utils/colors.dart';
import 'package:instagram_clone_flutter/utils/global_variable.dart';
import 'package:instagram_clone_flutter/utils/utils.dart';
import 'package:instagram_clone_flutter/widgets/text_field_input.dart';