import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:igclone/resources/auth_methods.dart';
import 'package:igclone/resources/firestore_methods.dart';
import 'package:igclone/screens/login_screen.dart';
import 'package:igclone/utils/colors.dart';
import 'package:igclone/utils/utils.dart';
import 'package:igclone/widgets/follow_button.dart';